// webview-react/src/ui/ErrorBoundary.tsx
import { Component, ReactNode } from 'react';

interface ErrorInfo {
  componentStack: string;
  errorBoundary: string;
}

interface Props {
  children: ReactNode;
  fallbackMessage?: string;
  showDetails?: boolean;
  onError?: (error: Error, errorInfo: ErrorInfo) => void;
}

interface State {
  hasError: boolean;
  error: Error | null;
  errorInfo: ErrorInfo | null;
}

class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      hasError: false,
      error: null,
      errorInfo: null
    };
  }

  static getDerivedStateFromError(error: Error): Partial<State> {
    return {
      hasError: true,
      error
    };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    const customErrorInfo: ErrorInfo = {
      componentStack: errorInfo.componentStack || '',
      errorBoundary: this.constructor.name
    };

    this.setState({
      errorInfo: customErrorInfo
    });

    if (this.props.onError) {
      this.props.onError(error, customErrorInfo);
    }

    console.error('ErrorBoundary caught an error:', error, errorInfo);

    // Log Radix-specific errors for debugging
    if (error.message && (error.message.includes('radix') || error.message.includes('CSS var'))) {
      console.error('Radix UI or CSS variable error detected:', error.message);
    }
  }

  handleReload = () => {
    this.setState({
      hasError: false,
      error: null,
      errorInfo: null
    });
    window.location.reload();
  };

  handleRetry = () => {
    this.setState({
      hasError: false,
      error: null,
      errorInfo: null
    });
  };

  render() {
    if (this.state.hasError) {
      return <ErrorFallback 
        error={this.state.error}
        errorInfo={this.state.errorInfo}
        fallbackMessage={this.props.fallbackMessage}
        showDetails={this.props.showDetails}
        onReload={this.handleReload}
        onRetry={this.handleRetry}
      />;
    }

    return this.props.children;
  }
}

interface ErrorFallbackProps {
  error: Error | null;
  errorInfo: ErrorInfo | null;
  fallbackMessage?: string;
  showDetails?: boolean;
  onReload: () => void;
  onRetry: () => void;
}

const ErrorFallback: React.FC<ErrorFallbackProps> = ({
  error,
  errorInfo,
  fallbackMessage = "Something went wrong",
  showDetails = false,
  onReload,
  onRetry
}) => {
  return (
    <div className="flex flex-col items-center justify-center h-screen p-8 text-center">
      <div className="max-w-lg p-8 rounded border">
        <div className="mb-6 text-red-400">
          <h1 className="text-xl font-semibold flex items-center justify-center gap-2">
            <span className="text-2xl">❌</span>
            Oops! Something went wrong
          </h1>
        </div>
        
        <div>
          <p className="mb-6 opacity-80">
            {fallbackMessage}
          </p>

          {showDetails && error && (
            <div className="mt-6 p-4 bg-black/20 rounded border text-left font-mono text-sm max-h-[200px] overflow-auto">
              <p className="font-semibold text-sm">Error Details:</p>
              <div className="mt-2">
                <strong>Message:</strong> {error?.message || 'Unknown error'}
              </div>
              {error.stack && (
                <div className="mt-2">
                  <strong>Stack:</strong>
                  <pre className="whitespace-pre-wrap mt-1">
                    {error.stack}
                  </pre>
                </div>
              )}
              {errorInfo?.componentStack && (
                <div className="mt-2">
                  <strong>Component Stack:</strong>
                  <pre className="whitespace-pre-wrap mt-1">
                    {errorInfo.componentStack}
                  </pre>
                </div>
              )}
            </div>
          )}
          
          <div className="flex gap-4 mt-6 justify-center">
            <button
              className="flex items-center gap-2 rounded bg-[var(--vscode-button-background,#0e639c)] px-4 py-2 text-white hover:bg-[var(--vscode-button-hoverBackground,#1177bb)]"
              onClick={onRetry}
            >
              <span>🔄</span>
              Try Again
            </button>
            <button
              className="rounded border px-4 py-2 hover:bg-white/5"
              onClick={onReload}
            >
              Reload Page
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ErrorBoundary;

// webview/src/lib/components/ErrorBoundary.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { appActions } from '$lib/stores/appStore';
    import { registerCoreComponents } from '$lib/utils/fluentUI';

    // Register Fluent UI components
    registerCoreComponents();

    // Props
    export let fallbackMessage = 'Something went wrong. Please try again.';
    export let showDetails = false;
    export let onError: ((error: Error) => void) | null = null;

    // State
    let hasError = false;
    let errorMessage = '';
    let errorStack = '';
    let errorDetails = '';

    // Error handler
    function handleError(error: Error | ErrorEvent | PromiseRejectionEvent) {
        hasError = true;
        
        if (error instanceof Error) {
            errorMessage = error.message;
            errorStack = error.stack || '';
            errorDetails = `${error.name}: ${error.message}`;
        } else if (error instanceof ErrorEvent) {
            errorMessage = error.message;
            errorStack = error.error?.stack || '';
            errorDetails = `${error.filename}:${error.lineno}:${error.colno} - ${error.message}`;
        } else if (error instanceof PromiseRejectionEvent) {
            errorMessage = error.reason?.message || 'Promise rejection';
            errorStack = error.reason?.stack || '';
            errorDetails = `Unhandled Promise Rejection: ${error.reason}`;
        } else {
            errorMessage = 'Unknown error occurred';
            errorDetails = String(error);
        }

        // Log error for debugging
        console.error('ErrorBoundary caught error:', error);
        
        // Report to app store
        appActions.setError(errorMessage);
        
        // Call custom error handler if provided
        if (onError && error instanceof Error) {
            try {
                onError(error);
            } catch (handlerError) {
                console.error('Error in custom error handler:', handlerError);
            }
        }
    }

    // Reset error state
    function resetError() {
        hasError = false;
        errorMessage = '';
        errorStack = '';
        errorDetails = '';
        appActions.clearError();
    }

    // Reload the component/page
    function reloadComponent() {
        resetError();
        // Force a re-render by updating a reactive variable
        window.location.reload();
    }

    onMount(() => {
        // Global error handlers
        const handleGlobalError = (event: ErrorEvent) => {
            handleError(event);
        };

        const handleUnhandledRejection = (event: PromiseRejectionEvent) => {
            handleError(event);
        };

        // Add global error listeners
        window.addEventListener('error', handleGlobalError);
        window.addEventListener('unhandledrejection', handleUnhandledRejection);

        return () => {
            window.removeEventListener('error', handleGlobalError);
            window.removeEventListener('unhandledrejection', handleUnhandledRejection);
        };
    });

    // Reactive statement to catch component errors
    $: if (hasError) {
        console.warn('Component is in error state:', errorMessage);
    }
</script>

{#if hasError}
    <div class="error-boundary">
        <fluent-card class="error-card">
            <div class="error-content">
                <div class="error-icon">⚠️</div>
                <h3 class="error-title">Oops! Something went wrong</h3>
                <p class="error-message">{fallbackMessage}</p>
                
                {#if showDetails && errorDetails}
                    <details class="error-details">
                        <summary>Technical Details</summary>
                        <div class="error-details-content">
                            <p><strong>Error:</strong> {errorMessage}</p>
                            {#if errorStack}
                                <pre class="error-stack">{errorStack}</pre>
                            {/if}
                        </div>
                    </details>
                {/if}

                <div class="error-actions">
                    <fluent-button
                        appearance="accent"
                        on:click={resetError}
                        on:keydown={(e: KeyboardEvent) => e.key === 'Enter' && resetError()}
                        role="button"
                        tabindex="0"
                    >
                        Try Again
                    </fluent-button>

                    <fluent-button
                        on:click={reloadComponent}
                        on:keydown={(e: KeyboardEvent) => e.key === 'Enter' && reloadComponent()}
                        role="button"
                        tabindex="0"
                    >
                        Reload
                    </fluent-button>
                </div>
            </div>
        </fluent-card>
    </div>
{:else}
    <slot />
{/if}

<style>
    .error-boundary {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 200px;
        padding: 20px;
    }

    .error-card {
        max-width: 500px;
        width: 100%;
        padding: 30px;
        text-align: center;
    }

    .error-content {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 15px;
    }

    .error-icon {
        font-size: 48px;
        margin-bottom: 10px;
    }

    .error-title {
        margin: 0;
        color: var(--vscode-errorForeground);
        font-size: 20px;
        font-weight: 600;
    }

    .error-message {
        margin: 0;
        color: var(--vscode-foreground);
        font-size: 16px;
        line-height: 1.5;
    }

    .error-details {
        width: 100%;
        margin-top: 15px;
        text-align: left;
    }

    .error-details summary {
        cursor: pointer;
        font-weight: 500;
        color: var(--vscode-textLink-foreground);
        margin-bottom: 10px;
    }

    .error-details summary:hover {
        color: var(--vscode-textLink-activeForeground);
    }

    .error-details-content {
        padding: 10px;
        background-color: var(--vscode-textCodeBlock-background);
        border-radius: 4px;
        border: 1px solid var(--vscode-panel-border);
    }

    .error-details-content p {
        margin: 0 0 10px 0;
        font-size: 14px;
    }

    .error-stack {
        margin: 0;
        padding: 10px;
        background-color: var(--vscode-editor-background);
        border: 1px solid var(--vscode-panel-border);
        border-radius: 3px;
        font-family: var(--vscode-editor-font-family);
        font-size: 12px;
        line-height: 1.4;
        color: var(--vscode-foreground);
        overflow-x: auto;
        white-space: pre-wrap;
        word-break: break-all;
    }

    .error-actions {
        display: flex;
        gap: 10px;
        margin-top: 20px;
    }

    .error-actions fluent-button {
        min-width: 100px;
    }

    /* Responsive design */
    @media (max-width: 600px) {
        .error-boundary {
            padding: 10px;
        }

        .error-card {
            padding: 20px;
        }

        .error-actions {
            flex-direction: column;
            width: 100%;
        }

        .error-actions fluent-button {
            width: 100%;
        }
    }
</style>
