// webview-react/src/App.tsx
import React, { useState, useEffect } from 'react';
import {
  FluentProvider,
  webLightTheme,
  webDarkTheme,
  Button,
  Input,
  Card,
  CardHeader,
  Text,
  Body1,
  Caption1
} from '@fluentui/react-components';
import { connectionMonitor, ConnectionState, ConnectionEvent } from '../../src/shared/connectionMonitor';

interface VSCodeAPI {
  postMessage: (message: any) => void;
  setState: (state: any) => void;
  getState: () => any;
}

declare global {
  interface Window {
    acquireVsCodeApi?: () => VSCodeAPI;
  }
}

function App() {
  const [status, setStatus] = useState('Initializing...');
  const [logs, setLogs] = useState<string[]>([]);
  const [vscode, setVscode] = useState<VSCodeAPI | null>(null);
  const [message, setMessage] = useState('');
  const [isDark, setIsDark] = useState(true);
  const [connectionState, setConnectionState] = useState<ConnectionState>(connectionMonitor.getState());
  const [reconnectProgress, setReconnectProgress] = useState<{ attempt: number; delay: number } | null>(null);

  const log = (msg: string) => {
    const timestamp = new Date().toISOString();
    setLogs(prev => [...prev, `${timestamp} - ${msg}`]);
  };

  const sendMessage = () => {
    if (message.trim()) {
      const messageData = {
        command: 'testMessage',
        data: message.trim(),
        timestamp: Date.now()
      };

      const sent = connectionMonitor.sendMessage(messageData);
      if (sent) {
        log(`Sent: ${message.trim()}`);
      } else {
        log(`Queued: ${message.trim()} (will send when connected)`);
      }
      setMessage('');
    }
  };

  useEffect(() => {
    log('React app mounted');

    let retries = 0;
    const maxRetries = 10;

    // Set up connection monitor event handlers
    const unsubscribeConnected = connectionMonitor.on('connected', (event: ConnectionEvent) => {
      setConnectionState(connectionMonitor.getState());
      setStatus('Connected to VS Code');
      log(`Connected - Latency: ${event.data?.latency || 0}ms`);
      setReconnectProgress(null);
    });

    const unsubscribeDisconnected = connectionMonitor.on('disconnected', (_event: ConnectionEvent) => {
      setConnectionState(connectionMonitor.getState());
      setStatus('Disconnected from VS Code');
      log('Connection lost - attempting to reconnect...');
    });

    const unsubscribeReconnecting = connectionMonitor.on('reconnecting', (event: ConnectionEvent) => {
      setConnectionState(connectionMonitor.getState());
      setReconnectProgress({ attempt: event.data.attempt, delay: event.data.delay });
      setStatus(`Reconnecting... (attempt ${event.data.attempt})`);
      log(`Reconnecting in ${event.data.delay}ms (attempt ${event.data.attempt})`);
    });

    const unsubscribeError = connectionMonitor.on('error', (event: ConnectionEvent) => {
      setConnectionState(connectionMonitor.getState());
      log(`Connection error: ${event.data.message}`);
    });

    const unsubscribeHeartbeat = connectionMonitor.on('heartbeat', (_event: ConnectionEvent) => {
      setConnectionState(connectionMonitor.getState());
    });

    const initVSCode = () => {
      if (typeof window !== 'undefined' && window.acquireVsCodeApi) {
        try {
          const api = window.acquireVsCodeApi();
          setVscode(api);
          setStatus('VS Code API acquired successfully');
          log('VS Code API acquired');

          // Initialize connection monitor
          connectionMonitor.initialize(api);

          // Send ready message
          api.postMessage({
            command: 'webviewReady',
            source: 'react-app',
            timestamp: Date.now()
          });
          log('Sent webviewReady message');

          // Listen for messages from extension
          const handleMessage = (event: MessageEvent) => {
            const msg = event.data;

            // Handle heartbeat responses
            if (msg.command === 'heartbeatResponse') {
              connectionMonitor.handleHeartbeatResponse(msg.timestamp);
              return;
            }

            log(`Received from extension: ${JSON.stringify(msg)}`);
          };

          window.addEventListener('message', handleMessage);

          return () => {
            window.removeEventListener('message', handleMessage);
            connectionMonitor.destroy();
            unsubscribeConnected();
            unsubscribeDisconnected();
            unsubscribeReconnecting();
            unsubscribeError();
            unsubscribeHeartbeat();
          };
          
        } catch (error) {
          setStatus(`Error acquiring VS Code API: ${error}`);
          log(`Error: ${error}`);
        }
      } else if (retries < maxRetries) {
        retries++;
        setStatus(`VS Code API not ready, retry ${retries}/${maxRetries}`);
        log(`Retry ${retries}/${maxRetries}`);
        setTimeout(initVSCode, 100);
      } else {
        setStatus('VS Code API unavailable after retries');
        log('Failed to acquire VS Code API after retries');
      }
    };
    
    initVSCode();
  }, []);

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      sendMessage();
    }
  };

  return (
    <FluentProvider theme={isDark ? webDarkTheme : webLightTheme}>
      <div style={{ padding: '16px', height: '100vh', overflow: 'auto' }}>
        <Card>
          <CardHeader
            header={<Text weight="semibold">React Webview Test</Text>}
            action={
              <Button
                size="small"
                onClick={() => setIsDark(!isDark)}
              >
                {isDark ? 'Light' : 'Dark'}
              </Button>
            }
          />
          
          <div style={{ padding: '16px' }}>
            <div style={{
              padding: '8px 12px',
              borderRadius: '4px',
              margin: '8px 0',
              backgroundColor: status.includes('successfully') ? '#063b49' :
                             status.includes('Error') ? '#5a1d1d' : '#664d00',
              border: `1px solid ${status.includes('successfully') ? '#007acc' :
                                 status.includes('Error') ? '#be1100' : '#ffcc00'}`
            }}>
              <Body1>Status: {status}</Body1>
            </div>

            {/* Connection Status */}
            <div style={{ display: 'flex', gap: '12px', margin: '8px 0', flexWrap: 'wrap' }}>
              <div style={{
                padding: '4px 8px',
                borderRadius: '12px',
                backgroundColor: connectionState.isConnected ? '#063b49' : '#5a1d1d',
                border: `1px solid ${connectionState.isConnected ? '#007acc' : '#be1100'}`
              }}>
                <Caption1>{connectionState.isConnected ? '🟢 Connected' : '🔴 Disconnected'}</Caption1>
              </div>

              {connectionState.isConnected && (
                <>
                  <div style={{
                    padding: '4px 8px',
                    borderRadius: '12px',
                    backgroundColor: connectionState.connectionQuality === 'excellent' ? '#063b49' :
                                   connectionState.connectionQuality === 'good' ? '#664d00' : '#5a1d1d',
                    border: `1px solid ${connectionState.connectionQuality === 'excellent' ? '#007acc' :
                                       connectionState.connectionQuality === 'good' ? '#ffcc00' : '#be1100'}`
                  }}>
                    <Caption1>Quality: {connectionState.connectionQuality}</Caption1>
                  </div>

                  <div style={{
                    padding: '4px 8px',
                    borderRadius: '12px',
                    backgroundColor: '#664d00',
                    border: '1px solid #ffcc00'
                  }}>
                    <Caption1>Latency: {connectionState.latency}ms</Caption1>
                  </div>
                </>
              )}

              {reconnectProgress && (
                <div style={{
                  padding: '4px 8px',
                  borderRadius: '12px',
                  backgroundColor: '#664d00',
                  border: '1px solid #ffcc00'
                }}>
                  <Caption1>Reconnecting... ({reconnectProgress.attempt})</Caption1>
                </div>
              )}
            </div>
            
            <div style={{ display: 'flex', gap: '8px', margin: '16px 0', alignItems: 'center' }}>
              <Input
                value={message}
                onChange={(_, data) => setMessage(data.value)}
                onKeyDown={handleKeyPress}
                placeholder="Type a test message"
                style={{ flex: 1 }}
              />
              
              <Button
                appearance="primary"
                disabled={!vscode || !message.trim()}
                onClick={sendMessage}
              >
                Send Message
              </Button>
            </div>
            
            <div style={{ marginTop: '16px' }}>
              <Text weight="semibold">Logs:</Text>
              <div style={{
                backgroundColor: '#0f0f0f',
                border: '1px solid #3c3c3c',
                borderRadius: '4px',
                padding: '8px',
                maxHeight: '200px',
                overflowY: 'auto',
                marginTop: '8px'
              }}>
                <Caption1 style={{ fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
                  {logs.join('\n')}
                </Caption1>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </FluentProvider>
  );
}

export default App;

// webview-simple/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    provideFluentDesignSystem,
    fluentButton,
    fluentTextField,
    fluentCard
  } from '@fluentui/web-components';
  import { connectionMonitor } from '../../src/shared/connectionMonitor.ts';

  // Register Fluent UI components
  provideFluentDesignSystem().register(fluentButton(), fluentTextField(), fluentCard());

  let status = 'Initializing...';
  let logs: string[] = [];
  let vscode: any = null;
  let message = '';
  let connectionState = connectionMonitor.getState();
  let reconnectProgress: { attempt: number; delay: number } | null = null;

  function log(msg: string) {
    const timestamp = new Date().toISOString();
    logs = [...logs, `${timestamp} - ${msg}`];
  }

  function sendMessage() {
    if (message.trim()) {
      const messageData = {
        command: 'testMessage',
        data: message.trim(),
        timestamp: Date.now()
      };

      const sent = connectionMonitor.sendMessage(messageData);
      if (sent) {
        log(`Sent: ${message.trim()}`);
      } else {
        log(`Queued: ${message.trim()} (will send when connected)`);
      }
      message = '';
    }
  }

  onMount(() => {
    log('App mounted');

    let retries = 0;
    const maxRetries = 10;

    // Set up connection monitor event handlers
    const unsubscribeConnected = connectionMonitor.on('connected', (event) => {
      connectionState = connectionMonitor.getState();
      status = 'Connected to VS Code';
      log(`Connected - Latency: ${event.data?.latency || 0}ms`);
      reconnectProgress = null;
    });

    const unsubscribeDisconnected = connectionMonitor.on('disconnected', (event) => {
      connectionState = connectionMonitor.getState();
      status = 'Disconnected from VS Code';
      log('Connection lost - attempting to reconnect...');
    });

    const unsubscribeReconnecting = connectionMonitor.on('reconnecting', (event) => {
      connectionState = connectionMonitor.getState();
      reconnectProgress = { attempt: event.data.attempt, delay: event.data.delay };
      status = `Reconnecting... (attempt ${event.data.attempt})`;
      log(`Reconnecting in ${event.data.delay}ms (attempt ${event.data.attempt})`);
    });

    const unsubscribeError = connectionMonitor.on('error', (event) => {
      connectionState = connectionMonitor.getState();
      log(`Connection error: ${event.data.message}`);
    });

    const unsubscribeHeartbeat = connectionMonitor.on('heartbeat', (event) => {
      connectionState = connectionMonitor.getState();
    });

    function initVSCode() {
      if (typeof window !== 'undefined' && (window as any).acquireVsCodeApi) {
        try {
          vscode = (window as any).acquireVsCodeApi();
          status = 'VS Code API acquired successfully';
          log('VS Code API acquired');

          // Initialize connection monitor
          connectionMonitor.initialize(vscode);

          // Send ready message
          vscode.postMessage({
            command: 'webviewReady',
            source: 'simple-svelte',
            timestamp: Date.now()
          });
          log('Sent webviewReady message');

          // Listen for messages from extension
          window.addEventListener('message', (event) => {
            const msg = event.data;

            // Handle heartbeat responses
            if (msg.command === 'heartbeatResponse') {
              connectionMonitor.handleHeartbeatResponse(msg.timestamp);
              return;
            }

            log(`Received from extension: ${JSON.stringify(msg)}`);
          });
          
        } catch (error) {
          status = `Error acquiring VS Code API: ${error}`;
          log(`Error: ${error}`);
        }
      } else if (retries < maxRetries) {
        retries++;
        status = `VS Code API not ready, retry ${retries}/${maxRetries}`;
        log(`Retry ${retries}/${maxRetries}`);
        setTimeout(initVSCode, 100);
      } else {
        status = 'VS Code API unavailable after retries';
        log('Failed to acquire VS Code API after retries');
      }
    }
    
    initVSCode();
  });
</script>

<main>
  <fluent-card>
    <h2>Simple Svelte Webview Test</h2>
    
    <div class="status" class:success={status.includes('successfully')} class:error={status.includes('Error')}>
      Status: {status}
    </div>

    <!-- Connection Status -->
    <div class="connection-status">
      <div class="connection-indicator" class:connected={connectionState.isConnected} class:disconnected={!connectionState.isConnected}>
        {connectionState.isConnected ? '🟢 Connected' : '🔴 Disconnected'}
      </div>

      {#if connectionState.isConnected}
        <div class="quality-indicator" class:excellent={connectionState.connectionQuality === 'excellent'} class:good={connectionState.connectionQuality === 'good'} class:poor={connectionState.connectionQuality === 'poor'}>
          Quality: {connectionState.connectionQuality}
        </div>

        <div class="latency-indicator">
          Latency: {connectionState.latency}ms
        </div>
      {/if}

      {#if reconnectProgress}
        <div class="reconnect-indicator">
          Reconnecting... ({reconnectProgress.attempt})
        </div>
      {/if}
    </div>
    
    <div class="controls">
      <fluent-text-field
        value={message}
        placeholder="Type a test message"
        role="textbox"
        tabindex="0"
        on:input={(e) => message = e.target.value}
        on:keydown={(e) => e.key === 'Enter' && sendMessage()}
      ></fluent-text-field>

      <fluent-button
        appearance="accent"
        disabled={!vscode || !message.trim()}
        role="button"
        tabindex="0"
        on:click={sendMessage}
        on:keydown={(e) => (e.key === 'Enter' || e.key === ' ') && sendMessage()}
      >
        Send Message
      </fluent-button>
    </div>
    
    <div class="logs">
      <h3>Logs:</h3>
      <pre>{logs.join('\n')}</pre>
    </div>
  </fluent-card>
</main>

<style>
  :global(body) {
    margin: 0;
    padding: 8px;
    font-family: var(--vscode-font-family, 'Segoe UI', sans-serif);
    background: var(--vscode-editor-background, #1e1e1e);
    color: var(--vscode-foreground, #cccccc);
  }

  main {
    max-width: 100%;
  }

  fluent-card {
    padding: 16px;
    display: block;
  }

  .status {
    padding: 8px 12px;
    border-radius: 4px;
    margin: 8px 0;
    background: var(--vscode-inputValidation-warningBackground, #664d00);
    border: 1px solid var(--vscode-inputValidation-warningBorder, #ffcc00);
  }

  .status.success {
    background: var(--vscode-inputValidation-infoBackground, #063b49);
    border-color: var(--vscode-inputValidation-infoBorder, #007acc);
  }

  .status.error {
    background: var(--vscode-inputValidation-errorBackground, #5a1d1d);
    border-color: var(--vscode-inputValidation-errorBorder, #be1100);
  }

  .connection-status {
    display: flex;
    gap: 12px;
    margin: 8px 0;
    flex-wrap: wrap;
  }

  .connection-indicator, .quality-indicator, .latency-indicator, .reconnect-indicator {
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 12px;
    border: 1px solid;
  }

  .connection-indicator.connected {
    background: var(--vscode-inputValidation-infoBackground, #063b49);
    border-color: var(--vscode-inputValidation-infoBorder, #007acc);
  }

  .connection-indicator.disconnected {
    background: var(--vscode-inputValidation-errorBackground, #5a1d1d);
    border-color: var(--vscode-inputValidation-errorBorder, #be1100);
  }

  .quality-indicator.excellent {
    background: var(--vscode-inputValidation-infoBackground, #063b49);
    border-color: var(--vscode-inputValidation-infoBorder, #007acc);
  }

  .quality-indicator.good {
    background: var(--vscode-inputValidation-warningBackground, #664d00);
    border-color: var(--vscode-inputValidation-warningBorder, #ffcc00);
  }

  .quality-indicator.poor {
    background: var(--vscode-inputValidation-errorBackground, #5a1d1d);
    border-color: var(--vscode-inputValidation-errorBorder, #be1100);
  }

  .latency-indicator, .reconnect-indicator {
    background: var(--vscode-inputValidation-warningBackground, #664d00);
    border-color: var(--vscode-inputValidation-warningBorder, #ffcc00);
  }

  .controls {
    display: flex;
    gap: 8px;
    margin: 16px 0;
    align-items: center;
  }

  fluent-text-field {
    flex: 1;
  }

  .logs {
    margin-top: 16px;
  }

  .logs pre {
    background: var(--vscode-textCodeBlock-background, #0f0f0f);
    border: 1px solid var(--vscode-panel-border, #3c3c3c);
    border-radius: 4px;
    padding: 8px;
    max-height: 200px;
    overflow-y: auto;
    font-size: 12px;
    white-space: pre-wrap;
  }
</style>
